name: Build and Publish

on:
  push:
    branches:
      - main  # Trigger on pushes to the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up .NET SDK
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'

    - name: Restore .NET dependencies
      run: |
        cd ./ModManagerCore
        dotnet restore

    - name: Build .NET project
      run: |
        cd ./ModManagerCore
        dotnet build --configuration Release

    - name: Publish .NET project
      run: |
        cd ./ModManagerCore
        dotnet publish --configuration Release --output ../publish/Core

    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies for Python
      run: |
        python -m pip install --upgrade pip
        pip install PySide6 pyinstaller

    - name: Build ModManagerGUI with PyInstaller
      run: |
        cd ../ModManagerGUI
        pyinstaller --add-data "../publish/Core:Core" --name ModManagerGUI --windowed main.py

    - name: Artifacts
      run: |
        echo "Build can be found in ModManagerGUI/dist/ModManagerGUI"
